#!/usr/bin/env bash
# configuration of Ngix web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html
sudo echo Hello World! > /var/www/html/index.nginx-debian.html
sudo service nginx restart
