#!/usr/bin/env bash
# confgure to add costum header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
config=\
'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
	add_header X-Served-By \$hostname;

        server_name _;

        location /redirect_me {
                return 301 https://youtu.be/7VAI73roXaY;
        }
}'
echo -e "$config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
